version: 2

builds:
  - binary: oshiv
    id: oshiv
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=readonly
    ldflags:
      - "-s -w -X 'github.com/cnopslabs/oshiv/cmd.version={{.Version}}'"

release:
  prerelease: auto

universal_binaries:
  - replace: true

checksum:
  name_template: 'checksums.txt'

brews:
  - name: oshiv
    description: "Tool for finding and connecting to OCI instances"
    homepage: "https://github.com/cnopslabs/oshiv"
    license: "MIT"
    install: |
      bin.install "oshiv"
    repository:
      owner: cnopslabs
      name: oshiv
    directory: Formula
