builds:
  - binary: oshiv
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: askcloudhelloworld
    homepage: https://github.com/cnopslabs/oshiv
    tap:
      owner: cnopslabs
      name: homebrew-cnopslabs
    commit_author:
      name: rozdolsky33
      email: rozdolskyvolodymyr@gmail.com

checksum:
  name_template: 'checksums.txt'