version: 2

builds:
  - binary: oshiv
    id: oshiv
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
    ldflags:
      - "-s -w -X 'github.com/cnopslabs/oshiv/cmd.version={{.Version}}'"


release:
  prerelease: auto

universal_binaries:
  - replace: true

checksum:
  name_template: 'checksums.txt'