# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oshiv < Formula
  desc "Tool for finding and connecting to OCI instances"
  homepage "https://github.com/cnopslabs/oshiv"
  version "1.2.1"
  license "MIT"

  on_macos do
    url "https://github.com/cnopslabs/oshiv/releases/download/v1.2.1/oshiv_1.2.1_darwin_all.tar.gz"
    sha256 "6b656d9a5014bf651a5c5b5c02df613867591f2db144583493769582b279a7e7"

    def install
      bin.install "oshiv"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cnopslabs/oshiv/releases/download/v1.2.1/oshiv_1.2.1_linux_amd64.tar.gz"
        sha256 "c10b41b26510a4cbb2d993fb33fe85bbd21e4beda598fda86124e9209857c320"

        def install
          bin.install "oshiv"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cnopslabs/oshiv/releases/download/v1.2.1/oshiv_1.2.1_linux_arm64.tar.gz"
        sha256 "49d60bdb1737fa12b5ae108d88a210803f420f90ea471618521c6c002af311af"

        def install
          bin.install "oshiv"
        end
      end
    end
  end
end
