# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oshiv < Formula
  desc "Tool for finding and connecting to OCI instances"
  homepage "https://github.com/cnopslabs/oshiv"
  version "1.2.2"
  license "MIT"

  on_macos do
    url "https://github.com/cnopslabs/oshiv/releases/download/v1.2.2/oshiv_1.2.2_darwin_all.tar.gz"
    sha256 "a71e40df83619de4dc116d38062547b817528aabff18b8165b0055521ce807aa"

    def install
      bin.install "oshiv"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cnopslabs/oshiv/releases/download/v1.2.2/oshiv_1.2.2_linux_amd64.tar.gz"
        sha256 "584cd8d3b32ead3e08346c2f74c0944ad97a938907dcea06c7b544bc7a27fdda"

        def install
          bin.install "oshiv"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cnopslabs/oshiv/releases/download/v1.2.2/oshiv_1.2.2_linux_arm64.tar.gz"
        sha256 "f96631828519628dbc71334d8809d7dc7d2ac9a008efaa0357add94b0764e16d"

        def install
          bin.install "oshiv"
        end
      end
    end
  end
end
