# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oshiv < Formula
  desc "Tool for finding and connecting to OCI instances"
  homepage "https://github.com/cnopslabs/oshiv"
  version "1.2.0"
  license "MIT"

  on_macos do
    url "https://github.com/cnopslabs/oshiv/releases/download/v1.2.0/oshiv_1.2.0_darwin_all.tar.gz"
    sha256 "8b0c5a3ab306c2a3e1caa7a7e8423057a59db188d950b9fdf38bd5023dff9eb1"

    def install
      bin.install "oshiv"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cnopslabs/oshiv/releases/download/v1.2.0/oshiv_1.2.0_linux_amd64.tar.gz"
        sha256 "ff5d65d168299503c4b0dcc2c05200dbe5b303d1e154f0511c056e926e2db76b"

        def install
          bin.install "oshiv"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cnopslabs/oshiv/releases/download/v1.2.0/oshiv_1.2.0_linux_arm64.tar.gz"
        sha256 "5364ad15cd25a5a2efe2e0c77f98c2baa8f227bbd3bb283cf01613b02fbdbbde"

        def install
          bin.install "oshiv"
        end
      end
    end
  end
end
