# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oshiv < Formula
  desc "Tool for finding and connecting to OCI instances"
  homepage "https://github.com/cnopslabs/oshiv"
  version "2.0.0"
  license "MIT"

  on_macos do
    url "https://github.com/cnopslabs/oshiv/releases/download/v2.0.0/oshiv_2.0.0_darwin_all.tar.gz"
    sha256 "a36cde7d29ebe82807ad047ccceb3e876c161b748246393702486d2040281a14"

    def install
      bin.install "oshiv"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/cnopslabs/oshiv/releases/download/v2.0.0/oshiv_2.0.0_linux_amd64.tar.gz"
      sha256 "cdf50a1d55539033c4b672675fe345e9f320c76c21960217e653fa189026a4f8"
      def install
        bin.install "oshiv"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/cnopslabs/oshiv/releases/download/v2.0.0/oshiv_2.0.0_linux_arm64.tar.gz"
      sha256 "ed47471bfcd3ab339d1ab3f5b0892b58bff4f92d5b3cc308fb316b4d614ed9e7"
      def install
        bin.install "oshiv"
      end
    end
  end
end
