name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release (e.g., v1.0.0)'
        required: true
        default: ''

  push:
    tags:
      - 'v*'

jobs:
  release:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            git fetch --all
            git checkout ${{ github.event.inputs.tag }}
          fi

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Install Staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Install Zip on Windows
        if: runner.os == 'Windows'
        run: choco install zip -y

      - name: Verify environment
        run: make check-env

      - name: Install dependencies
        run: go mod tidy

      - name: Build binary for native platform
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          make clean
          make install-local

      - name: Compress binary
        run: zip build/oshiv_${{ github.ref_name }}_${{ matrix.os }}.zip build/*

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Release ${{ github.ref_name }} with pre-built binaries.
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binary asset to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/
          asset_name: oshiv_${{ github.ref_name }}_${{ matrix.os }}.zip
          asset_content_type: application/zip