name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release (e.g., v1.0.0)'
        required: true
        default: ''

  push:
    tags:
      - 'v*'

jobs:
  release:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            git fetch --all
            git checkout ${{ github.event.inputs.tag }}
          fi

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Verify environment
        run: make check-env

      - name: Install dependencies
        run: go mod tidy

      - name: Build and package binaries
        run: |
          make clean
          make release

      - name: Upload release assets
        uses: actions/upload-artifact@v3
        with:
          name: release-binaries
          path: build/

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Release ${{ github.ref_name }} with pre-built binaries.
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binary assets to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/
          asset_name: oshiv_${{ github.ref_name }}_binaries.zip
          asset_content_type: application/zip